### ISSUE TITLE
Double menu option on "Add a message" screen (Extension version 18.0.0)

### ISSUE THREAD

**Issue by robert-byrne** [lucasschneider/mpl-koha-patch-WE#3]
"Include notes for returned mail and bad emails:" toggle option under "Add a new message" appears twice. Although we are running one minor version behind, none of the change logs seem to mention this being solved, and the issue is not present in an older version (The now "deprecated" version of the Koha patch, version 17.1.1 does not have this issue.) Steps to reproduce:
(with version 18.0.0 of Koha patch enabled, and presumably version 18.0.0.1)
1)Click on "Add a new message" under a patron account.
2) The check box appears twice on the next menu.
This issue is present in Firefox 48.0.2, but the same version of Firefox with the now "deprecated" version of the extension does not have this issue.

**Comment by lucasschneider** [comment]
Fixed in v18.0.3.
