### ISSUE TITLE
Entering Fine description auto-capitalizes. (Koha extension version 18.0.0)

### ISSUE THREAD

**Issue by robert-byrne** [lucasschneider/mpl-koha-patch-WE#4]
When clicking outside of the entry field for fine description, the text inside the entry field becomes capitalized. The text does not change to capitalized until AFTER the field is unselected. I have double checked that the caps-lock key is NOT ON when the description is typed. This has occurred several times now when clicking the pay all button, as the text field is unselected after the button is pressed. My estimate is this is a koha patch issue, not an issue with koha itself since the only thing changed in our environment today was the update to version 18.0.0 of the koha patch (The "new version", updating from the now "deprecated version.") Steps to reproduce:
1) While fines are present on an account, click on the fines tab to open the list of outstanding fines.
2)Next, either click pay or pay all (the issue occurs with both)
3) Finally, type in a sample description, and click pay on the fine. 
4) The text switches CAPS in the description field as it is processing the request and advancing the page. This CAPS font persists under the account history.
This issue is present in Firefox 48.0.2, but the same version of Firefox with the now "deprecated" version of the extension does not have this issue.

**Comment by lucasschneider** [comment]
Fixed in v18.0.1!

**Comment by robert-byrne** [comment]
Thanks, I'll suggest that we update the version we are using in production then to use the new version of the extension!
