### ISSUE TITLE
Autofilling PSTAT and Zip Code in Edit/ Create New Patron screen sometimes autofills wrong information.(Koha extension version 18.0.0) 

### ISSUE THREAD

**Issue by robert-byrne** [lucasschneider/mpl-koha-patch-WE#5]
When editing or creating a new card, the autofill for PSTAT and Zip code sometimes fills with the previously created cards information. Sometimes this persists if you try to re-calculuate (clicking into address box and tabbing out to try to have script run again), other times it evaluates correctly. This results in potential for incorrect information in the patron's account.
Steps to reproduce:
1)Create an account and fill out all necessary information, including autofilling pstat and zip.
2) Create a second account. Try to put in a DIFFERENT address and city state.
3) when trying to tab or click out of field and have it autofill the pstat/zip, the previous address will display in the "autofill note" and the previous address's zip code and PSTAT will be autofilled instead of the current address's PSTAT.
4)Clicking again or tabbing out of the city, state section doesn't use the new address, but clicking into the zip code section seems to function properly? (tab autoadvance not working but function is ran, but clicking in the box might make it update properly?)
This is problematic because it results in incorrect information under a patrons account. This only occurs when switching the version of the extension from 17.1.1 to the newer versions of 18.0.1 We are using Firefox 48.0.2

**Comment by lucasschneider** [comment]
Fixed in version 19.0.0.
